### ISSUE TITLE
Conflicto con Grilla en AboutUs.

### ISSUE THREAD

**Issue by TomasSampayo** [TomasSampayo/coffe#4]
uk-container y uk-grid conflictuan entre si.

**Comment by yaeru** [comment]
que tipo de conflicto? jamas deben ir juntas en el mismo elento esas clases

**Comment by TomasSampayo** [comment]
aca tengo una grilla con dos columnas. Como puedo darle el los margenes de .uk-container?.
<img width="1680" alt="Captura de Pantalla 2021-11-15 a la(s) 16 32 03" src="https://user-images.githubusercontent.com/75331656/141843154-c4bb009c-a84b-41c6-8431-15e4c58ea07b.png">
r

**Comment by yaeru** [comment]
uk container es para otra cosa diferente, por favor lee la documentacion de uikit en ese caso.
Un div con container y despues la grilla es algo que va adentro, no todo en lo mismo, no tengas miedo a poner mas divs

lo ideal es como el proyecto de solar, para eso lo tenemos de referencia, ahi esta bien puesto
