### ISSUE TITLE
to do

### ISSUE THREAD

**Issue by TomasSampayo** [TomasSampayo/coffe#5]
acomodar carpetas dentro de assets. 
sacar imagenes de public.
buscar en imagenes.
modal.
boton de ver info en cards.

**Comment by yaeru** [comment]
@TomasSampayo consejo: utiliza un issue para cada tarea en vez de un listado, asi a medida que las vas terminando, cerras los issues

**Comment by TomasSampayo** [comment]
Ok!. Ahi los hago.
